### ISSUE TITLE
[Feature Request] grafana dashboard

### ISSUE THREAD

**Issue by yunw** [yesoreyeram/grafana-azure-datasource#12]
**Is your feature request related to a problem? Please describe.**
It takes me quite long time to figure out the query while building the grafana dashboard while using the plugin. 
Is it possible sharing the grafana dashboard as well? the example looks very impressive

**Comment by yesoreyeram** [comment]
Hi @yunw - I have added sample dashboard at [here](https://github.com/yesoreyeram/grafana-azure-datasource/blob/master/src/dashboards/azure-cost-by-subscription.json). 

If you are updating the plugin, this is now included in the plugin itself. So you can directly import the dashboard in grafana.

Note : There is a breaking change in the new version (v0.1.0). You may need to reconfigure the data source in grafana. Refer the [CHANGELOG.md](https://github.com/yesoreyeram/grafana-azure-datasource/blob/master/CHANGELOG.md) for details.
