### ISSUE TITLE
Unit

### ISSUE THREAD

**Issue by planet4** [yesoreyeram/grafana-azure-datasource#15]
Great work, However I can not figure out why I get this in £. I would like to have it in swedish SEK. In Azure I do get SEK, I could not either change the unit in Grafana. I am running the latest version.

**Comment by yesoreyeram** [comment]
Thanks for reporting this. I will check

**Comment by planet4** [comment]
My bad, I replaced the Json file with CurrencySEK and it works fine. Now I will just solve the problem that it only finds one subscription. I have 3. I do find them in our monitoring system check Mk so the permissions seems to be fine.

**Comment by yesoreyeram** [comment]
See if changing the variable definition / refresh helps

![image](https://user-images.githubusercontent.com/153843/89286031-65607b80-d649-11ea-8a42-482410c07082.png)

**Comment by yesoreyeram** [comment]
To change the units, check the panel options. 

![image](https://user-images.githubusercontent.com/153843/89286283-d0aa4d80-d649-11ea-8665-22410493aa63.png)

Unfortunately, Grafana doesn't support variables for units. So you need to change individual panels if you are using template dashboard.

I am closing this issue for unit. If require create a bug for subscriptions not appearing separately. 

Thanks for trying the plugin and providing your feedback.  If you can star the repository, that is much appreciated.
