### ISSUE TITLE
[Help Required] Title

### ISSUE THREAD

**Issue by leon-andria** [yesoreyeram/grafana-azure-datasource#18]
Looks like the plugin doesn't support Grafana v7.1.5
Plugin Azure Plus doesn't exist when trying to install it.

**Comment by yesoreyeram** [comment]
How are you installing?

**Comment by leon-andria** [comment]
I go to https://grafana.com/grafana/dashboards/12732 and use the ID.

**Comment by yesoreyeram** [comment]
You need to install the plugin first as mentioned here. https://github.com/yesoreyeram/grafana-azure-datasource#installation This plugin won't come with grafana by default.

**Comment by leon-andria** [comment]
Oh, I misunderstood it. My mistake, now it's clear and confirm it's working 👍
