### ISSUE TITLE
[Help Required] Installation and Configuration 

### ISSUE THREAD

**Issue by tbayer1995** [yesoreyeram/grafana-azure-datasource#19]
Hi there,

I am attempting to install and configure the Grafana Azure Plus Datasource so that I can leverage the Azure Cost Analysis dashboard. I have installed the plugin and verified it exists in the `/var/lib/grafana/plugins` directory.

When trying to add the 'Azure Plus' data source in the Grafana UI, I am running into an error of 'Object prototype may only be an Object or null: undefined evaluating http://my-private-ip/public/plugins/yesoreyeram-azure-datasource/module.js Loading plugins/yesoreyeram-azure-datasource/module

It seems that Grafana is trying to pull the plugin from `/public/plugins/` and not `/var/lib/grafana/plugins` where it is installed. Where can I update this path to have it pull from the correct directory?

Also when trying to access the plugin I get stuck on loading at the following screen: 
![image](https://user-images.githubusercontent.com/70603186/91896827-12391300-ec5f-11ea-8cfc-e5ac15f48ae6.png)

Additionally, you mention provisioning the datasource via a file. Where does this file exist/where should we create it? I have created a service principal with the required permissions, but I am unsure where to store it's configurations.

Any help you can provide would be greatly appreciated.

**Comment by yesoreyeram** [comment]
If you are not familiar with external plugins / [provisioning process](https://grafana.com/docs/grafana/latest/administration/provisioning/#provisioning-grafana), try manual installation like below.

Following commands did work for me. give a try and let me know.

```

## Download Grafana
mkdir grafana-installation-demo
cd grafana-installation-demo/
wget https://dl.grafana.com/oss/release/grafana-7.1.5.linux-amd64.tar.gz
tar -zxvf grafana-7.1.5.linux-amd64.tar.gz
cd grafana-7.1.5/

## Install plugin
mkdir -p data/plugins/
cd data/plugins/
wget https://github.com/yesoreyeram/grafana-azure-datasource/archive/master.zip
unzip master.zip

'## Start Grafana
cd ../../
bin/grafana-server
```

![image](https://user-images.githubusercontent.com/153843/91901114-a921c180-ec97-11ea-9f94-6a0b555a812e.png)
![image](https://user-images.githubusercontent.com/153843/91901460-23eadc80-ec98-11ea-9eba-e6d3f12ee045.png)
![image](https://user-images.githubusercontent.com/153843/91901508-3a913380-ec98-11ea-90fa-5a38e24478d3.png)
![image](https://user-images.githubusercontent.com/153843/91901400-159cc080-ec98-11ea-9d80-01258452891f.png)

**Comment by tbayer1995** [comment]
This worked great, thank you very much.

One other question, is there a way to change the pounds sign to a $ sign? I checked our monthly spend for our subscription, and the amount is correct, but it is showing a pound sign instead of a $ sign.

Any thoughts?

Thank you!

**Comment by yesoreyeram** [comment]
Glad to hear that.

Checkout this https://github.com/yesoreyeram/grafana-azure-datasource/issues/15 for changing the unit.
