### ISSUE TITLE
Is this plugin published anywhere?

### ISSUE THREAD

**Issue by PavelPikat** [yesoreyeram/grafana-azure-datasource#2]
Hello

This plugin looks very interesting - is it published anywhere and how do I install it?
I'm interested in Azure Resource Graph

**Comment by yesoreyeram** [comment]
Hi @PavelPikat - Thanks for sharing your interest. The plugin is not published yet. Plan is to bring the feature native into grafana.  As i am busy with my day stuff, this is getting delayed.  https://github.com/grafana/grafana/pull/18629

BTW, I am using this plugin in our production environments. So feel free to use and report any bugs or issues.

**Comment by PavelPikat** [comment]
Do I just download the source and copy it to plugins folder?

**Comment by PavelPikat** [comment]
Figured out I needed to get the sources, install packages and run the build task. Then copy dist folder to Gragana's plugins folder

**Comment by shaybenb** [comment]
> Figured out I needed to get the sources, install packages and run the build task. Then copy dist folder to Gragana's plugins folder

hi
can you share the command and the work flow of what need to do ?
thanks

**Comment by yesoreyeram** [comment]
README.md file now updated with more installation instructions.

**Comment by javaadpatel** [comment]
@yesoreyeram would really like to use this on my hosted Grafana instance, any idea when you would publish this? Any assistance I can give you to get it published?

**Comment by yesoreyeram** [comment]
Hi @javaadpatel  - Thanks for the interested. Let me know what kind of support you can offer. Mostly, creating bugs/pull requests will help me to proceed further.
