### ISSUE TITLE
[bug] helm installation failed

### ISSUE THREAD

**Issue by mrafieee** [yesoreyeram/grafana-azure-datasource#20]
**Describe the bug**
used helm chart installation and got this.

**Screenshots**
│ Installing plugin with id [https://github.com/yesoreyeram/grafana-azure-datasource/archive/master.zip                │
│ Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error                     │
│ stream closed

**Version Details:**
 - Grafana version : 
 - chart version : 3.4.0

**Comment by yesoreyeram** [comment]
Can you check the url and provide valid zip url from the release page. I can confirm it works with helm chart. 

If you can provide more details of the error, i can definetly reopen this issue.
