### ISSUE TITLE
[Feature Request] Add support for Alerting

### ISSUE THREAD

**Issue by al-lac** [yesoreyeram/grafana-azure-datasource#21]
Hi, please add the option to enable Alerting. We would really like to be alerted if the usage per day exceeds a certain amount.

**Comment by yesoreyeram** [comment]
Hi @al-lac - thanks for reaching out. 

I don't have any plans to convert this into backend plugin. Currently grafana only supports alerting for backend plugins.  BTW, Why can't you use azure alerts directly?

**Comment by al-lac** [comment]
Hi @yesoreyeram, thanks for the quick response! 

Too bad, then i will probably have to look for some prometheus exporter or write one myself. 

We already have azure alerts setup, but they only allow to alert when a certain threshold of a budget is reached. So basically you could go through a lot of your budget in one day until you get an alert.

**Comment by yesoreyeram** [comment]
Alright. But that's not the end. May be in future grafana have native support for this.

BTW, if u can share the prom exporter once ready. Will be useful for others.

**Comment by al-lac** [comment]
That would be awesome. 

Will do for sure! Do you a good starting point for the Azure Cost API?

**Comment by yesoreyeram** [comment]
Hi @al-lac - i don't have anything specific. But you can search for azure documents.
