### ISSUE TITLE
[Help Required] Trying to use transformation on Monthly cost and divide it by another field output

### ISSUE THREAD

**Issue by intikhabalam** [yesoreyeram/grafana-azure-datasource#23]
I am trying to divide the monthly expenses by no of users. But when i use transformation, nothing show on graph 

The requirement is to get expense per user. I added a new query and get no of user from my database. I used the mixed datasource and added one query from Azure-Plus datasource and get monthly expense. I have added another query and retrieved no of users from my sql database. Then i used transform tab and divided azure-plus field by sql-db output. Grafana does not show anything.

The problem is azure-plus monthly cost deliver 2 fields (date and cost) and sql-db output deliver 1 field( no of users). Is there a way to get only 1 field from azure-plus monthly cost (only cost)? 

![azure-plus issue](https://user-images.githubusercontent.com/5160147/95269166-538f9480-0895-11eb-8a8f-a59ac24eccf5.png)

**Comment by yesoreyeram** [comment]
@intikhabalam  this is more or less relate to grafana transformation. Nothing to do with the plugin. So I suggest go to grafana community or slack for more details about grafana transformation
