### ISSUE TITLE
Account balance monitoring

### ISSUE THREAD

**Issue by abashkinas** [yesoreyeram/grafana-azure-datasource#24]
Hello, can you please tell me if it is possible to configure a request in this data source from grafana so that the balance of funds in the azure account is displayed?

**Comment by yesoreyeram** [comment]
Hi @abashkinas what do you mean balance of funds in azure ? How to you setup that in azure? 

I didn't came across sich thing in azure before. So looking for more details. I am closing this now. If you can provide more details, i can reopen definitely.
