### ISSUE TITLE
cant connect to tenant "Failed to connect."

### ISSUE THREAD

**Issue by gosterm** [yesoreyeram/grafana-azure-datasource#26]
I am trying to connect to my tenant but I keep getting "Failed to connect."
I created a new app to connect. Maybe there is not enough rights there. But since the error is so general how can I find out what is wrong, are there any more specific logs avalable?
I am thinking that if there is some right issue, where Exactly does it connect to so we can check that rights.

thank you

**Comment by gosterm** [comment]
I went subscription to subscription and added the reqired rights to my app

**Comment by yesoreyeram** [comment]
What you need is "monitoring reader" or "reader" access your management group level. So you can avoid giving permissions for multiple individual subscriptions.  So one place to control permissions.

If you have already created account for in-built grafana azure data source, you can reuse the same credentials. No additional permissions required for this datasource.

**Comment by gosterm** [comment]
I believe that it exists but I just couldn't find it for the tenant level. It would be nice "one for all" but I didn't find it. I search mainly via azure ad but didn't found an appropriate role.

**Comment by yesoreyeram** [comment]
if you are assigning access at root/tenant level, you may need to elevate your access as suggested here. https://docs.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin

**Comment by gosterm** [comment]
Yes I have such rights. But I cannot find how to assign the app the right "one for all" not at subscription by subscription. Having said that:
I am happy with the result our dashboard is working so I just wanted to say kudos, great dashboard!

As far as I am concerned you helped me enough I have already closed the issue...

best regards
