### ISSUE TITLE
[Bug] Title 

### ISSUE THREAD

**Issue by shaybenb** [yesoreyeram/grafana-azure-datasource#7]
**Describe the bug**
no output its comeing to grafana.

yestrady its work fain , but today i dont get any data.

**Screenshots**
![2](https://user-images.githubusercontent.com/46863888/83940092-ab849480-a7ea-11ea-84ba-1b18c8c84741.PNG)

**Version Details:**
 - Grafana version : latest
 - Plugin version : latest

**Additional context**

**Comment by yesoreyeram** [comment]
What is the time range in your dashboard? Minimum granularity the azure API provides is 1day. So time range expected is minimum last 24 hours.

**Comment by shaybenb** [comment]
ok ,so the best is to change to 1 day ?
now i can see that its grab the data.

also can you plaseee share of of the dashborad ??? 

your repo is help me alot , i can querey all my azure build in 1 place !!!

thanks alot for that

**Comment by yesoreyeram** [comment]
@shaybenb glad to hear that the plugin is useful to you. Unfortunately, i can't share the dashboard as it has some sensitive information. But I am open to clarify any doubts you have.
