### ISSUE TITLE
Plugin not loading in Grafana

### ISSUE THREAD

**Issue by kkadiyam** [yesoreyeram/grafana-azure-datasource#9]
**Describe the bug**
We have clones the repository to the plugins directory.
Restarted Grafana

 We are able to see the Grafana plugin in UI, But, When we try to open and configure the page got stuck (Loading for more than 15 mins)
Also, Can you add any instructions after npm install ?, How to use the plugin etc,...

**Screenshots**

**Version Details:**
 - Grafana version : 
 - Plugin version :

**Additional context**

**Comment by yesoreyeram** [comment]
Plugin should load automatically once you download the zip file and extracted to your plugin folder. No need to any other setup like `npm install`. Everything is pre-built and compiled version is in dist folder.

### Downloading the plugin zip file

![image](https://user-images.githubusercontent.com/153843/87565868-1e224300-c6ba-11ea-88b1-50029b2dfb7f.png)
